"""Initial schema

Revision ID: 76423a30fede
Revises: 
Create Date: 2026-03-11 16:16:17.106033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76423a30fede'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('dna_snapshots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('week', sa.String(length=20), nullable=False),
    sa.Column('genre_breakdown', sa.JSON(), nullable=True),
    sa.Column('mood_breakdown', sa.JSON(), nullable=True),
    sa.Column('top_artists', sa.JSON(), nullable=True),
    sa.Column('calculated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dna_snapshots_user_id'), 'dna_snapshots', ['user_id'], unique=False)
    op.create_table('likes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('spotify_track_id', sa.String(length=100), nullable=False),
    sa.Column('track_name', sa.String(length=500), nullable=True),
    sa.Column('artist_name', sa.String(length=500), nullable=True),
    sa.Column('album_name', sa.String(length=500), nullable=True),
    sa.Column('album_image', sa.String(length=500), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('preview_url', sa.String(length=500), nullable=True),
    sa.Column('liked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_likes_spotify_track_id'), 'likes', ['spotify_track_id'], unique=False)
    op.create_index(op.f('ix_likes_user_id'), 'likes', ['user_id'], unique=False)
    op.create_table('listening_history',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('spotify_track_id', sa.String(length=100), nullable=False),
    sa.Column('track_name', sa.String(length=500), nullable=True),
    sa.Column('artist_name', sa.String(length=500), nullable=True),
    sa.Column('genre', sa.String(length=100), nullable=True),
    sa.Column('played_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('play_duration', sa.Integer(), nullable=True),
    sa.Column('skipped', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_listening_history_user_id'), 'listening_history', ['user_id'], unique=False)
    op.create_table('lyra_messages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lyra_messages_user_id'), 'lyra_messages', ['user_id'], unique=False)
    op.create_table('playlists',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('cover_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_playlists_user_id'), 'playlists', ['user_id'], unique=False)
    op.create_table('ratings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('spotify_track_id', sa.String(length=100), nullable=False),
    sa.Column('track_name', sa.String(length=500), nullable=True),
    sa.Column('artist_name', sa.String(length=500), nullable=True),
    sa.Column('album_image', sa.String(length=500), nullable=True),
    sa.Column('stars', sa.Integer(), nullable=False),
    sa.Column('rated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ratings_spotify_track_id'), 'ratings', ['spotify_track_id'], unique=False)
    op.create_index(op.f('ix_ratings_user_id'), 'ratings', ['user_id'], unique=False)
    op.create_table('playlist_songs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('playlist_id', sa.String(length=36), nullable=False),
    sa.Column('spotify_track_id', sa.String(length=100), nullable=False),
    sa.Column('track_name', sa.String(length=500), nullable=True),
    sa.Column('artist_name', sa.String(length=500), nullable=True),
    sa.Column('album_name', sa.String(length=500), nullable=True),
    sa.Column('album_image', sa.String(length=500), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('preview_url', sa.String(length=500), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('added_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['playlist_id'], ['playlists.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_playlist_songs_playlist_id'), 'playlist_songs', ['playlist_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_playlist_songs_playlist_id'), table_name='playlist_songs')
    op.drop_table('playlist_songs')
    op.drop_index(op.f('ix_ratings_user_id'), table_name='ratings')
    op.drop_index(op.f('ix_ratings_spotify_track_id'), table_name='ratings')
    op.drop_table('ratings')
    op.drop_index(op.f('ix_playlists_user_id'), table_name='playlists')
    op.drop_table('playlists')
    op.drop_index(op.f('ix_lyra_messages_user_id'), table_name='lyra_messages')
    op.drop_table('lyra_messages')
    op.drop_index(op.f('ix_listening_history_user_id'), table_name='listening_history')
    op.drop_table('listening_history')
    op.drop_index(op.f('ix_likes_user_id'), table_name='likes')
    op.drop_index(op.f('ix_likes_spotify_track_id'), table_name='likes')
    op.drop_table('likes')
    op.drop_index(op.f('ix_dna_snapshots_user_id'), table_name='dna_snapshots')
    op.drop_table('dna_snapshots')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
